<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl; ?>/css/images/promass_ico.png">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Zend</title>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl; ?>/js/highcharts.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/themes/gray.js"></script>
    </head>
    <body>
        <div id="wrapper">

            <div id="content">
                <?php echo $this->layout()->content; ?><div class="clear"></div>
            </div><!-- end content-->
            <div id="footer">
                    <p>2011 Copyright © Protec All Rights Reserved.</p>
            </div><!-- end footer-->
        </div>
    </body>
</html>
