<?php //echo $this->baseUrl;exit; ?>
<script type="text/javascript">
$(document).ready(function() {
    /*
    $("#hola").click(function(){
        //alert("Hola Miguel Angel");
    });
    */
    
    var chart; // global
    
    /**
    * Request data from the server, add it to the graph and set a timeout to request again
    */
    function requestData() {
        $.ajax({
            url: "<?php echo $this->url(array('controller' => 'graficas',  
            'action' => 'server')); ?>",
            success: function(point) {
                var series = chart.series[0],
                    shift = series.data.length > 20; // shift if the series is longer than 20

                // add the point
                chart.series[0].addPoint(point, true, shift);

                // call it again after one second
                setTimeout(requestData, 1000);    
            },
            cache: false
        });
    }
    
    chart = new Highcharts.Chart({
        chart: {
            renderTo: 'container',
            defaultSeriesType: 'spline',
            events: {
                load: requestData
            }
        },
        title: {
            text: 'Datos aleatorios en vivo'
        },
        xAxis: {
            type: 'datetime',
            tickPixelInterval: 150,
            maxZoom: 20 * 1000
        },
        yAxis: {
            minPadding: 0.2,
            maxPadding: 0.2,
            title: {
                text: 'Valor',
                margin: 80
            }
        },
        series: [{
            name: 'Datos aleatorios',
            data: []
        }]
    });
    
    //Cambiamos el titulo
    $("#hola").click(function(){
        chart.title.text = "Cambiamos el titulo de la grafica";
        //alert("Hola Miguel Angel");
    });
});
</script>

<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 600px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Graficas<span id="zf-name">Highcharts!</span></h1>

    <h3>Ejemplos de graficas</h3>

    <div id="more-information">
        <a id="hola" href="#">Hola</a>
        <div id="container" style="width: 100%; height: 400px"></div>
<!--        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>-->
<!--        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>-->
    </div>
</div>